name: lab2
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter 
  
  dio: ^5.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '^3.0.0'
  
flutter:
  uses-material-design: true